### PR TITLE
MVP

### PR DESCRIPTION
**Pull request by thatsamhopkins**
@ajvera @JSumulong @TrRo26 Hey y'all, I've implemented feedback through a query param and changed our redirect for when the game is over. Going to start working on stats now.

### CODE REVIEW

**Comment by thatsamhopkins** [comment]
With these changes, we appear to have a MVP. I'd be happy to keep working on this to add users and track user stats.

**Comment by thatsamhopkins** [comment]
I'd be happy to write the logic/controller for additional features (multiple users, profile pages) if someone else wants to make the display. we'd need the following displays: login page, add login/logout button to all views depending if user is logged in, user profile page displaying stats for an array of the user's played rounds that will be provided by the controller. we could also potentially update the game-over stats page to show the high scores for the deck that was just played. let me know what you think! :)

**Comment by ajvera** [comment]
@hopkins571 happy to help with any of the items you mentioned above.

Let me know which ones you would like me to help with!

**Comment by TrRo26** [comment]
Thanks for all your work on this, Sam! Let me know if there's anything else that needs to be done.

**Pull request merged**
